// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLaCViUTIqi_qkcEPwLOHhCnaVj1By0uc',
    appId: '1:238959161445:web:b56782076717551a4e168c',
    messagingSenderId: '238959161445',
    projectId: 'careplus01',
    authDomain: 'careplus01.firebaseapp.com',
    storageBucket: 'careplus01.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBm6o5eo_9Q9-4xk-l_f6uF4jJpj4vO7UE',
    appId: '1:238959161445:android:40554e566a5a253d4e168c',
    messagingSenderId: '238959161445',
    projectId: 'careplus01',
    storageBucket: 'careplus01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRTvjDvOpfEP6RnF1WNCIIgAmYgp_C2Do',
    appId: '1:238959161445:ios:1869e570357b648e4e168c',
    messagingSenderId: '238959161445',
    projectId: 'careplus01',
    storageBucket: 'careplus01.firebasestorage.app',
    iosBundleId: 'com.example.carePlus',
  );
}
